<?php /** @var $this DigitalPianism_CampaignMonitor_Block_Adminhtml_System_Config_Form_Field_Refreshtoken */ ?>

<?php $refreshTokenUrl = Mage::helper("adminhtml")->getUrl("adminhtml/campaignmonitor/refreshtoken"); ?>
<button class="scalable save" type="button" title="Refresh Token" onclick="setLocation('<?php echo $refreshTokenUrl; ?>')">
    <span>
        <span>
            <span>Refresh Token</span>
        </span>
    </span>
</button>
