<?php
$helper = Mage::helper('campaignmonitor');
if (Mage::helper('campaignmonitor')->isCheckoutNewsletterEnabled()): ?>
	<li id="register-customer-newsletter">
		<input type="checkbox" name="billing[is_subscribed]" value="1" title="<?php echo Mage::helper('customer')->__('Sign Up for Newsletter') ?>" id="billing:is_subscribed"<?php echo ($this->isChecked() || $helper->isCheckoutNewsletterChecked())?' checked="checked"':'' ?> /> 
		<label for="billing:is_subscribed">
			<?php echo Mage::helper('customer')->__('Sign Up for Newsletter') ?>
		</label>
	</li>
	
	<script type="text/javascript">
	//<![CDATA[
	Element.show('register-customer-newsletter');
	var hasRunHideCheckoutNewsletter = false;
	jQuery(document).ready(function() {
		// add fix so it only runs once, checks checkout-step-billing & hasRunHideCheckoutNewsletter
		hideCheckoutNewsletter = function () {
			if (jQuery('#checkout-step-billing').is(":visible") && !hasRunHideCheckoutNewsletter && typeof(checkout) != 'undefined'){
				if (checkout.method == 'register'){
					<?php if (!$helper->isCheckoutNewsletterVisibleRegister()): ?>
						Element.hide('register-customer-newsletter');
						$('billing:is_subscribed').checked = false;
					<?php else: ?>
						Element.show('register-customer-newsletter');
						<?php if ($this->isChecked() || $helper->isCheckoutNewsletterChecked()): ?>
							$('billing:is_subscribed').checked = true;
						<?php endif ?>
					<?php endif ?>
				}
				else if (checkout.method == 'guest'){
					<?php if (!$helper->isCheckoutNewsletterVisibleGuest()): ?>
						Element.hide('register-customer-newsletter');
						$('billing:is_subscribed').checked = false;
					<?php else: ?>
						Element.show('register-customer-newsletter');
						<?php if ($this->isChecked() || $helper->isCheckoutNewsletterChecked()): ?>
							$('billing:is_subscribed').checked = true;
						<?php endif ?>
					<?php endif ?>
				}
				hasRunHideCheckoutNewsletter = true;
			}
		}
		setInterval("hideCheckoutNewsletter()", 100);
	});
	//]]>
	</script>
<?php endif ?>